### ISSUE TITLE
Add some missed icons

### ISSUE THREAD

**Issue by Mosi2772** [worron/ACYLS#4] opened 2016-09-04 04:41 UTC
1)Sublime Text (added)
2)Docky
3)Musique (added)
4)Tomahawk (added)
5)Telegram
6)Persepolis Download Manager( https://github.com/alireza-amirsamimi/persepolis ) (added)

Icons Problem
Log out
Shut Down
reboot
![6](https://cloud.githubusercontent.com/assets/21367642/18229086/5f711324-727f-11e6-87a4-5e9e817b0200.png)

**Comment by worron** [comment] 2016-09-04 16:13
Ok, I will take a look.

**Comment by worron** [comment] 2016-09-05 14:56
Add some missed icons.
All the rest (docky, browser, power control) are already in pack, seems you have some local trouble. To solve it I should know exact names of problem icons in your system. Find desktop file of certain application in `/usr/share/applications`, open it with any text editor and check line with `Icon= `. This way you can find the real name of missed icon, then report it here.

**Comment by Mosi2772** [comment] 2016-09-06 02:17
Docky
#1
![8](https://cloud.githubusercontent.com/assets/21367642/18259760/d6d7a5ee-73fc-11e6-8476-0b6c80a5bf6b.png)
#2 
![9](https://cloud.githubusercontent.com/assets/21367642/18259831/91f8c5a6-73fd-11e6-9ab9-bcd250ae808e.jpg)

**Comment by Mosi2772** [comment] 2016-09-06 02:31
Shutdown >> gnome-session-quit --power-off
Reboot >> gnome-session-quit --reboot
LogOut>> gnome-session-quit --logout
![11](https://cloud.githubusercontent.com/assets/21367642/18260062/b6a023a2-73ff-11e6-9a35-1d85bb4c4851.png)

**Comment by worron** [comment] 2016-09-06 13:34
Unfortunately I can't help if icon  displayed correctly in main menu and has wrong visual in dock. It's dock problem.

About power icons I need information about `Icon=` line, not `Exec=`.

**Comment by Mosi2772** [comment] 2016-09-07 10:37
Shutdown>>Icon=/usr/share/unity/icons/shutdown_highlight.png
LogOut>>Icon=/usr/share/unity/icons/logout_highlight.png
reboot>>Icon=/usr/share/unity/icons/restart_highlight.png

Public Folder & Templates In /home/username/

Some missed Format
.css
.cpp
.srt
.txt
![selection_007](https://cloud.githubusercontent.com/assets/21367642/18309046/b5890d36-750c-11e6-89a8-a49cdb5267e8.jpg)

**Comment by worron** [comment] 2016-09-07 14:38
If absolute path like `Icon=/usr/share/unity/icons/logout_highlight.png` settled in desktop file that meant current icon cannot be changed with theme. If you really want do this you can edit desktop file to change icon. Something like `Icon=gnome-logout` should be ok.

Missed folders confirmed. It will take some time to fix since new icon should be added to every alternative group. Can you open separete issue for this topic? It is more practical have standalone thread for diffrent missed icon/icon group and allow to solve problem step by step.

About missed formats. Actually, it is not necessary to have unique icon for every file type. For example `txt` files is ok with general text document icon. May be I can add  something for`cpp` and `css` but this is low priority task. And this is also question for separete issue.

**Comment by worron** [comment] 2016-09-10 14:48
Close this one since missed folders was added with 04c52a1.

**Closed by worron** 2016-09-10 14:48 UTC
