### ISSUE TITLE
Missing Icons in Systray

### ISSUE THREAD

**Issue by koegs** [worron/ACYLS#5] opened 2016-09-27 08:33 UTC
Hi,

i am glad somebody took the time to bring back ACYL.

On Ubuntu 16.04 (XFCE, awesomewm) there are so far missing icons in the systray:
blueman-applet (any state)
nm-applet (ethernet, ethernet with vpn lock symbol)

And just in case, is there a good and easy way to find out which icons such a tray-icon uses and where should the tray icons be placed?

**Comment by worron** [comment] 2016-09-27 15:14
![tray-icons-xfce](https://cloud.githubusercontent.com/assets/10406966/18879533/ac54be48-84e5-11e6-825e-8dcacb8ae940.png)

Can't reproduce with Xubuntu 16.04. It would be helpful if you provide exact names of missed icons. Unfortunately, I don't know any really reliable way to find out tray icon location. With a high probability network and bluetooth state icons are located in `status` folder of your default theme.

**Comment by koegs** [comment] 2016-09-28 08:15
Ok, i wasnt precise enough. As you said in XFCE it seems to be ok, but in awesome wm with a smaller bar different icons are used.

**Comment by worron** [comment] 2016-09-28 16:11
Ок, problem with blueman-applet confirmed. I add several missed blueman icons with b10d10d. Check it please.

Still can't figure what's wrong with nm-applet, it works all ok for me. I'm afraid it can't be fixed until we find exact names of missed icons.

**Comment by koegs** [comment] 2016-09-29 07:59
Blueman-applet is fixed. I did a research regarding the nm-applet and i think the missing icons are nm-device-wired.svg and nm-device-wired-secure.svg

**Comment by worron** [comment] 2016-09-29 13:04
Great. Two icons were added with d00f599. Please test it and report if problem was solved.

**Comment by koegs** [comment] 2016-09-29 13:11
It works, thank you very much.

**Comment by koegs** [comment] 2016-09-29 13:59
Well, wired is fixed, but nm-device-wireless-secured.pvg should be added too...

**Comment by worron** [comment] 2016-09-29 14:30
Ok, I will add 'nm-signal-*-secure' icons soon.

But I can't see 'nm-device-wireless-secured' among icons in my distro. That's named for sure? Where did you find it exactly?

**Comment by koegs** [comment] 2016-09-29 14:51
I think it was some misleading information from my google search. nm-signal-*-secure.svg is the correct answer. Just forget about nm-device-wireless-secure.

**Comment by worron** [comment] 2016-09-29 16:51
All 'nm-signal-*-secure' were added with bb39d45. Please report if it's fixed now.

**Comment by worron** [comment] 2016-10-07 15:52
Closed since no recent activity. Feel free to reopen if any new details come out.

**Closed by worron** 2016-10-07 15:52 UTC
